// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/statistic/service.go

// Package statistic is a generated GoMock package.
package statistic

import (
	gomock "github.com/golang/mock/gomock"
	types "github.com/junnotantra/go-shortener/internal/types"
	reflect "reflect"
)

// MockResource is a mock of Resource interface
type MockResource struct {
	ctrl     *gomock.Controller
	recorder *MockResourceMockRecorder
}

// MockResourceMockRecorder is the mock recorder for MockResource
type MockResourceMockRecorder struct {
	mock *MockResource
}

// NewMockResource creates a new mock instance
func NewMockResource(ctrl *gomock.Controller) *MockResource {
	mock := &MockResource{ctrl: ctrl}
	mock.recorder = &MockResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockResource) EXPECT() *MockResourceMockRecorder {
	return m.recorder
}

// UpdateStatistic mocks base method
func (m *MockResource) UpdateStatistic(statisticData types.StatisticData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatistic", statisticData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatistic indicates an expected call of UpdateStatistic
func (mr *MockResourceMockRecorder) UpdateStatistic(statisticData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatistic", reflect.TypeOf((*MockResource)(nil).UpdateStatistic), statisticData)
}

// GetStatisticInfo mocks base method
func (m *MockResource) GetStatisticInfo(uniqueString string) (types.StatisticData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatisticInfo", uniqueString)
	ret0, _ := ret[0].(types.StatisticData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatisticInfo indicates an expected call of GetStatisticInfo
func (mr *MockResourceMockRecorder) GetStatisticInfo(uniqueString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatisticInfo", reflect.TypeOf((*MockResource)(nil).GetStatisticInfo), uniqueString)
}
